version: 2
updates:
  - package-ecosystem: "docker"
    directories:
    - "/config/**/*"
    ignore:
    - dependency-name: fluxcd/helm-controller
    - dependency-name: fluxcd/image-automation-controller
    - dependency-name: fluxcd/image-reflector-controller
    - dependency-name: fluxcd/kustomize-controller
    - dependency-name: fluxcd/notification-controller
    - dependency-name: fluxcd/source-controller
    - dependency-name: linuxserver/bazarr
    - dependency-name: linuxserver/jackett
    - dependency-name: linuxserver/radarr
    - dependency-name: linuxserver/sabnzbd
    - dependency-name: linuxserver/sonarr
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
