---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-home
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: k8s-home
  timeout: 1m0s
  url: ssh://git@github.com/tun0/k8s-home

