---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-webhook
  namespace: flux-system
spec:
  type: github
  events:
    - ping
    - push
  secretRef:
    name: flux-webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: k8s-home
      namespace: flux-system
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: ghcr-webhook
  namespace: flux-system
spec:
  type: github
  events:
    - ping
    - registry_package
  secretRef:
    name: flux-webhook-token
  resources:
    - apiVersion: image.toolkit.fluxcd.io/v1
      kind: ImageRepository
      name: meter-reader-image
      namespace: flux-system
