---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: telegram
  namespace: flux-system
spec:
  providerRef:
    name: telegram
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: ImagePolicy
    name: '*'
  - kind: ImageRepository
    name: '*'
  - kind: ImageUpdateAutomation
    name: '*'
  - kind: Kustomization
    name: '*'
