---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Provider
metadata:
  name: telegram
  namespace: flux-system
spec:
  type: telegram
  channel: "637947592"
  secretRef:
    name: telegram-token
