apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: externaldns-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.17.0
        args:
        - --source=service
        - --domain-filter=local.tun0.eu
        - --zone-id-filter=26396c44703f98c7bf4402b4532acd92
        - --provider=cloudflare
        - --cloudflare-dns-records-per-page=5000
        envFrom:
        - secretRef:
            name: cloudflare-api-key
        resources: {}
