---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: frigate
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
  namespace: frigate
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
