---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: frigate.local.tun0.eu
  labels:
    app: frigate
  name: frigate
  namespace: frigate
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 5000
    targetPort: http
    protocol: TCP
    name: frigate
  - port: 8554
    targetPort: rtsp
    protocol: TCP
    name: rtsp
  selector:
    app: frigate
  type: LoadBalancer
  externalTrafficPolicy: Local
