---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: jackett-image
  namespace: flux-system
spec:
  image: linuxserver/jackett
  interval: 1h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: jackett-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jackett-image
  policy:
    semver:
      range: ^0.20
