---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: k8s-home
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      messageTemplate: |
        Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}

        Raw:
        {{ . }}
      author:
        email: fluxbot@tun0.nl
        name: FluxBot
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: k8s-home
