---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: k8s-home
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      messageTemplate: |
        Automated image update:{{ range $images := .Updated.Images }} {{ $images }}{{ end }}

        Automation name: {{ .AutomationObject }}

        Updates:
        {{ range $file, $fileresult := .Updated.Files -}}
          File: {{ $file }}
        {{ range $object, $imagerefs := $fileresult.Objects -}}
            Kind: {{ $object.APIVersion }}/{{ $object.Kind }}
            Name: {{ $object.Namespace }}/{{ $object.Name }}
        {{ range $imageref := $imagerefs -}}
              Image: {{ $imageref.Name }}
        {{ end -}}
        {{ end -}}
        {{ end }}

        ### YAML START ###
        ---
        automation: {{ .AutomationObject }}
        files:
        {{ range $file, $fileresult := .Updated.Files -}}
        -
          filename: {{ $file }}
          objects:
        {{ range $object, $imagerefs := $fileresult.Objects }}
          -
            apiVersion: {{ $object.APIVersion }}
            kind: {{ $object.Kind }}
            name: {{ $object.Name }}
            namespace: {{ $object.Namespace }}
            images:
        {{- range $imageref := $imagerefs }}
            -
              shortName: {{ $imageref.String }}
              fullName: {{ $imageref.Name }}
              registry: {{ $imageref.Registry }}
              repository: {{ $imageref.Repository }}
              identifier: {{ $imageref.Identifier }}
        {{ end -}}
        {{ end -}}
        {{ end -}}
        ### YAML END ###
      author:
        email: fluxbot@tun0.nl
        name: FluxBot
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: k8s-home
