---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: node-red-image
  namespace: flux-system
spec:
  image: nodered/node-red
  interval: 1h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: node-red-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: node-red-image
  policy:
    semver:
      range: ^3
