---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h0m0s
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: v1.11.1
  interval: 1h0m0s
  releaseName: longhorn
  values:
    persistence:
      reclaimPolicy: Retain
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort
    service:
      ui:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: longhorn.local.tun0.eu
        type: LoadBalancer
