---
kind: Service
apiVersion: v1
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: longhorn.local.tun0.eu
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.3.1
    app: longhorn-ui
  name: longhorn-frontend-lb
  namespace: longhorn-system
spec:
  type: LoadBalancer
  selector:
    app: longhorn-ui
  ports:
  - name: http
    port: 80
    targetPort: http
  loadBalancerIP: 192.168.178.207
  externalTrafficPolicy: Local
